---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: watcher
rules:
- apiGroups: [""]
  resources: ["pods", "events"]
  verbs: ["get", "watch", "list"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: watcher
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: watcher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: watcher
subjects:
  - kind: ServiceAccount
    name: watcher
    namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: watcher
  name: watcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: watcher
  template:
    metadata:
      labels:
        app: watcher
    spec:
      serviceAccount: watcher
      serviceAccountName: watcher
      containers:
      - image: duym/kubewatch
        imagePullPolicy: IfNotPresent
        name: watcher
        env:
          - name: SLACK_CHANNEL
            value: xxx
          - name: SLACK_TOKEN
            value: xxx
          - name: SLACK_TITLE
            value: alerting
